# Set Control + a as prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

#Scroll

set-option -g mouse on

# Set | and - for split

unbind %
unbind '"'

bind | split-window -h
bind - split-window -v

# Set vim-like bindings for switching windows

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
